version: 2
updates:
  - package-ecosystem: bun
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
    groups:
      bun-non-major:
        update-types:
          - minor
          - patch

  - package-ecosystem: cargo
    directory: "/native/local-host"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
    groups:
      cargo-non-major:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
    groups:
      actions-non-major:
        update-types:
          - minor
          - patch
